# Generated by Django 3.0.3 on 2020-03-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='tag_images/')),
                ('etc', models.CharField(max_length=10)),
            ],
        ),
    ]
