# Generated by Django 3.0.3 on 2020-03-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgup', '0002_tagimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagimage',
            name='image',
            field=models.ImageField(upload_to='tag_images'),
        ),
    ]
